config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'users_profiles/profile/:id', to: "users_profiles#profile", as: "user_profile"
  get 'users_profiles/instruments/:id', to: "users_profiles#instruments", as: "list_user_instruments"
  get 'users_profiles/rentals/:id', to: "users_profiles#rentals", as: "list_user_rentals"
  



  mount Attachinary::Engine => "/attachinary"

  get "instruments/:id/rent/confirm", to: "rentals#confirm", as: "confirm_rental"
  get "instruments/rent/error", to: "rentals#error", as: "rental_error"

  resources :instruments do
    resources :rentals, only: [:create]
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :instruments, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_title_description, :against => [:title, :description]

  has_attachment :photo

  belongs_to :user
  belongs_to :category

  validates :user_id, :category_id, :title, :description, :price, :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def self.search_by_category(category)
    Category.where(name: category.split(", ")).map(&:instruments).flatten!
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :instrument

  validate :validate_date_in_present, :validate_date_smaller_than_end_date, :validates_not_booked_yet
  validates :user_id, :instrument_id, :start_date, :end_date, presence: true

     # Return a scope for all rental overlapping the given rental, including the given rental itself
  #named_scope :overlapping, lambda { |rental| {

  #  :conditions => ["id <> ? AND (DATEDIFF(start_date, ?) * DATEDIFF(?, end_date)) >= 0", rental.id, rental.end_date, rental.start_date]
  #}}

  def validate_date_in_present
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "Please chose a start date that is in the present!")
    end
  end

  def validate_date_smaller_than_end_date
    if start_date.present? && start_date > end_date
      errors.add(:end_date, "Start date needs to be before end date!")
    end
  end


  def validates_not_booked_yet

    query = Rental.where("instrument_id = :instrument
      AND ((start_date - :start::date) * (:end::date - end_date)) >= 0", instrument: self.instrument_id, start: start_date, end: end_date)


    if query.count > 0
      errors.add(:end_date, "Already booked for these dates")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :instruments
  has_many :rentals

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_attachment :avatar

  def self.find_for_facebook_oauth(auth)
   user_params = auth.slice(:provider, :uid)
   user_params.merge! auth.info.slice(:email, :first_name, :last_name)
   user_params[:facebook_picture_url] = auth.info.image
   user_params[:token] = auth.credentials.token
   user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
   user_params = user_params.to_h

   user = User.find_by(provider: auth.provider, uid: auth.uid)
   user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
   if user
     user.update(user_params)
   else
     user = User.new(user_params)
     user.password = Devise.friendly_token[0,20]  # Fake password for validation
     user.save
   end

   return user
  end

  def user_avatar
    self.avatar.try(:path) || self.facebook_picture_url || "http://via.placeholder.com/50x50"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?



  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  def index
    @instruments = Instrument.all

    if params[:query].present?
      @instruments = @instruments.search_by_title_description(params[:query])
    end

    if params[:location].present?
      @instruments = @instruments.near(params[:location], 50)
    end

    if params[:category].present?
      @instruments = Instrument.search_by_category(params[:category])
    end

  end

  def show
    @rental = Rental.new
    @instrument = Instrument.find(params[:id])
    @instruments = Instrument.where.not(latitude: nil, longitude: nil)
    @instrument_coordinates = { lat: @instrument.latitude, lng: @instrument.longitude }
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @instrument.update(instrument_params)
      redirect_to instrument_path(@instrument)
    else
      render :edit
    end
  end

  def destroy
    @instrument.destroy
    respond_to do |format|
            format.html { redirect_to list_user_instruments_path(current_user) }
            format.js  # <-- idem
          end
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def instrument_params
    params.require(:instrument).permit(:title, :description, :location, :price, :photo, :category_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy, :confirm]

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @instrument = Instrument.find(params[:instrument_id])
    @rental.instrument = @instrument
    if @rental.save
      redirect_to instrument_path(@instrument), notice: "Rental created sucessfully"
    else
      #flash.now[:alert] = @rental.errors.full_messages.join(", ")
      render "instruments/show"
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :instrument_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_profiles_controller.rb
class UsersProfilesController < ApplicationController

  def profile
    @user = User.find(params[:id])
  end

  def instruments
    # @instruments = current_user.instruments
    @user = User.find(params[:id])
  end

  def rentals
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def search_results_phrase
    phrase = ""
    if params[:query].present? || params[:location].present?
      phrase = "Results "
    end
    if params[:query].present?
      phrase += "for '#{params[:query]}'"
    end
    if params[:location].present?
      phrase += " in #{params[:location].split('-')[0].strip}"
    end
    if params[:query].present? || params[:location].present?
      phrase += ":"
    end
    return phrase
  end

end

app/views/instruments/_datepicker.html.erb
<%= simple_form_for [@instrument, @rental] do |f| %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :start_date, input_html: {id: "datetimepicker1"}, as: :string %>
    </div>
    <div class="col-sm-6">
      <%= f.input :end_date, input_html: { id: "datetimepicker2" }, as: :string %>
    </div>
  </div>

  <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

<% content_for(:after_js) do %>
  <script type="text/javascript">

   $('#datetimepicker1').datetimepicker( {format: "DD/MM/YYYY" } );
   $('#datetimepicker2').datetimepicker( {format: "DD/MM/YYYY" } );

  </script>
<% end %>

app/views/instruments/_form.html.erb
<%= simple_form_for @instrument do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.association :category %>
  <%= f.input :price %>
  <%= f.input :location %>
  <%= f.input :photo, as: :attachinary %>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

<% content_for(:after_js) do %>
  <script type="text/javascript">
	  $(document).ready(function() {
	      var instrument_address = $('#instrument_location').get(0);

	      if (instrument_address) {
	        var autocomplete = new google.maps.places.Autocomplete(instrument_address, { types: ['address'] });
	        google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
	        google.maps.event.addDomListener(instrument_address, 'keydown', function(e) {
	        });
	      }
	  });

	  function onPlaceChanged() {
	    return this.getPlace();
	  }
  </script>
<% end %>

app/views/instruments/destroy.js.erb
$('[data-instrument-id=<%= @instrument.id %>]').slideUp();

app/views/instruments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h2>Edit Instrument</h2>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/instruments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h4 class="search-result">
        <%= search_results_phrase %>
      </h4>
    </div>
  </div>
  <div class="list-grid">
    <%= render '/shared/card' %>
  </div>
</div>

app/views/instruments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h2>Add new Instrument</h2>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/instruments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <ol class="breadcrumb">
        <li><%= link_to "Home", instruments_path %></li>
        <li><%= link_to "Instruments", instruments_path %></li>
        <li class="active"><%= @instrument.category.name %></li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="product-info product-header">
        <% if @instrument.photo? %>
          <%= cl_image_tag @instrument.photo.path, width: 600, height: 400, crop: :fill %>
        <% end %>
        <h1><%= @instrument.title %></h1>
        <p>
          <span class="fa fa-map-marker"></span>
          <%= @instrument.location %>
        </p>
      </div>
      <div class="product-info user-info">
        <div class="row">
          <div class="col-md-3">
            <%= cl_image_tag @instrument.user.user_avatar, class: "img-circle img-responsive" %>
          </div>
          <div class="col-md-9">
            <h4> <%= "#{@instrument.user.first_name}  #{@instrument.user.last_name}"%> </h4>
            <p><i class="fa fa-check-circle" aria-hidden="true"></i> Facebook Verified</p>
            <p><i class="fa fa-check-circle" aria-hidden="true"></i> Email Verified</p>
            <p><i class="fa fa-check-circle" aria-hidden="true"></i> Phone Number Verified</p>
          </div>
        </div>
      </div>
      <div class="product-info product-description">
        <div class="row">
          <div class="col-md-3">
            <h4>Description:</h4>
          </div>
          <div class="col-md-9">
            <p><%= @instrument.description %></p>
          </div>
        </div>
      </div>
      <div class="product-info product-location">
        <div class="row">
          <div class="col-md-3">
            <h4>Location:</h4>
          </div>
          <div class="col-md-9">
            <p><%= @instrument.location %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div id="map" style="width: 100%; height: 300px;"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <p> Price: <%= @instrument.price %></p>
      <% if user_signed_in? %>
        <%= render partial: "instruments/datepicker" %>
      <% else %>
        <%= link_to "Sign in now", new_user_session_path, class: "btn btn-danger btn-block" %>
      <% end %>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var location = <%= raw @instrument_coordinates.to_json %>;
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 14,
        center: location
      });
      var marker = new google.maps.Marker({
        position: location,
        map: map
      });
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Plug &amp; Play</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}&libraries=places" %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'bg/bg-hero.jpg'%>) ;">
  <div class="banner-content">
    <h1>Search it and be ready to rock!</h1>
    <%= render 'search_form' %>
  </div>
</div>

app/views/pages/_categories.html.erb
<h3 class="text-center">Featured Categories</h3>

<div class="home-list-grid">
    <%=link_to instruments_path(category: "Guitars, Bass, Orchestral Strings")  do %>
      <div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dohfsgcbx/image/upload/v1503060073/pexels-photo-258283_w39qoe.jpg');">
      <div class="banner-category-title">Strings</div>
      </div>
    <% end %>
    <%=link_to instruments_path(category: "Percussion Instruments") do %>
      <div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dohfsgcbx/image/upload/v1503060086/pexels-photo-241687_nmcloy.jpg');">
      <div class="banner-category-title">Drums</div>
      </div>
    <% end %>
    <%=link_to instruments_path(category: "Brass Instruments, Wind & Woodwinds") do %>
      <div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dohfsgcbx/image/upload/v1503060101/saxophone-music-gold-gloss-45243_gf2n5x.jpg');">
      <div class="banner-category-title">Winds</div>
      </div>
    <% end %>
    <%=link_to instruments_path(category: "Keyboards") do %>
      <div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dohfsgcbx/image/upload/v1503060111/public-domain-images-free-stock-photos-high-quality-resolution-downloads-around-the-house-22-1000x666_naolcf.jpg');">
      <div class="banner-category-title">Keyboards</div>
      </div>
    <% end %>
</div>

app/views/pages/_search_form.html.erb
<form action="<%= instruments_path %>" method="get">
  <div class="home-search">
      <div class="instrument-search-container">
        <label><span class="fa fa-search"></span> What are you looking for?</label>
        <input type="text" autocomplete="on" placeholder="e.g. Fender Twin" class="form-control search-term"
        name="query">
      </div>
      <div class="location-search-container">
        <label><span class="fa fa-map-marker"></span> Where are you looking?</label>
        <input type="text" placeholder="e.g. Austin, TX" class="form-control location-input" autocomplete="on" name="location">
      </div>
      <div class="text-center button-search">
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
  </div>
</form>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).ready(function() {
        var instrument_address = $('.location-input').get(0);

        if (instrument_address) {
          var autocomplete = new google.maps.places.Autocomplete(instrument_address, { types: ['(cities)'] });
          google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
          google.maps.event.addDomListener(instrument_address, 'keydown', function(e) {
          });
        }
    });

    function onPlaceChanged() {
      return this.getPlace();
    }
  </script>
<% end %>

app/views/pages/home.html.erb
<%= render 'banner' %>
<%= render 'categories' %>

app/views/rentals/_form.html.erb
<%= simple_form_for @rental do |f| %>
  <%= f.input :user_id %>
  <%= f.input :instrument_id %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/rentals/confirm.html.erb
confirm.html.erb

app/views/rentals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h2>Edit Rental</h2>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/rentals/error.html.erb
error.html.erb

app/views/rentals/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Rentals</h1>
      <%= link_to "Add a Rental", new_rental_path %>

      <div>
      <% @rentals.each do |rental| %>
      <h2><%= rental.id %></h2>
      <p><%= rental.start_date %>-<%= rental.end_date %></p>
      <%= link_to "details", rental_path(rental) %>
      <%= link_to "edit", edit_rental_path(rental) %>
      <%= link_to "delete", rental_path(rental), method: :delete %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h2>Add new rental</h2>

      <%= render "form" %>




    </div>
  </div>
</div>

app/views/rentals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1><%= @instrument.title %></h1>
      <p><%= @instrument.description %></p>
    </div>
    <div class="col-sm-6">
      <% if @instrument.photo? %>
        <%= cl_image_tag @instrument.photo.path, width: 200, height: 300, crop: :fit %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <p><%= @rental.start_date %>-<%= @rental.end_date %></p>
    </div>
  </div>
</div>

app/views/shared/_avatar_round_lg.html.erb
<img src='https://kitt.lewagon.com/placeholder/users/alex-felix' class="avatar-large"/>

app/views/shared/_avatar_round_sm.html.erb
<img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar"/>

app/views/shared/_avatar_round_sm_border.html.erb
<img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="avatar-bordered"/>

app/views/shared/_avatar_square_sm.html.erb
<img src='https://kitt.lewagon.com/placeholder/users/eschults' class="avatar-square"/>

app/views/shared/_card.html.erb
<% @instruments.each do |instrument| %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path instrument.photo.public_id %>')">
    <div class="card-category"><%= instrument.category.name %></div>
    <div class="card-description">
      <h2><%= instrument.title %></h2>
      <p><%= instrument.location %></p>
    </div>
    <%= cl_image_tag instrument.user.user_avatar, class: "card-user" %>
    <%= link_to "details", instrument_path(instrument), class: "card-link" %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Made with <i class="fa fa-music"></i> at Le Wagon
  </div>
</div>

app/views/shared/_message.html.erb
_message.html.erb

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "plug-n-play-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add an instrument!", new_instrument_path, class: "add-button" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.user_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to list_user_instruments_path(current_user) do %>
                <i class="fa fa-music"></i>  <%= t(".profile", default: "My Instruments") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users_profiles/_tabs.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to "Profile", user_profile_path %></li>
  <li><%= link_to "Instruments", list_user_instruments_path, class: "active" %></li>
</ul>

app/views/users_profiles/instruments.html.erb
<%= render "tabs" %>

<h3>My Instruments</h3>
<br>
<% @user.instruments.each do |instrument| %>

<div class="message" data-instrument-id="<%= instrument.id %>">
  <% if instrument.photo? %>
  <%= cl_image_tag instrument.photo.path, width: 400, height: 200, crop: :fill, class: "avatar-large" %>
  <% end %>
  <div class="message-name">
    <h3><%= instrument.title %></h3>
    <p><%= instrument.location %></p>
  </div>
  <div class="message-body">
    <h3>Price</h3>
    <p>$ <%= instrument.price %></p>
  </div>
  <div class="message-status">
    <ul class="list-inline product-controls">
      <li>
        <%= link_to "details", instrument_path(instrument), class: "btn-medium" %>
      </li>
      <li>
        <%= link_to "edit", edit_instrument_path(instrument), class: "btn-medium" %>
      </li>
      <li>
        <%= link_to "delete", instrument_path(instrument), method: :delete, remote: true, class: "btn-medium" %>
      </li>
    </ul>
  </div>
</div>

<% end %>

app/views/users_profiles/profile.html.erb
<%= render "tabs" %>

<div class="container">
	<div class="row">


		<div class="col-md-8 col-md-offset-2">

			<div class="panel panel-default">
				<div class="panel-body">

					<div class="box box-info">

						<div class="box-body">
							<div class="col-sm-6">
								<div  align="center"> <%= cl_image_tag current_user.user_avatar, class: "img-circle img-responsive profile-image1" %>


									<br>
									<div style="color:#999;" ><%= link_to "Edit Profile", edit_user_registration_path %></div>







								</div>

								<br>

              </div>
              <div class="col-sm-6">
                <h4 style="color:#00b1b1;"><%= current_user.first_name %> <%= current_user.last_name %></h4></span>
                <span><p><%= current_user.bio %></p></span>
              </div>
              <div class="clearfix"></div>
              <hr style="margin:5px 0 5px 0;">




              <div class="col-sm-5 col-xs-6 tital " >Member since:</div><div class="col-sm-7"><%= current_user.created_at %></div>

              <div class="clearfix"></div>
              <div class="bot-border"></div>

              <div class="col-sm-5 col-xs-6 tital " >Phone:</div><div class="col-sm-7"><%= current_user.phone %></div>

              <div class="clearfix"></div>
              <div class="bot-border"></div>

              <div class="col-sm-5 col-xs-6 tital " >Address:</div><div class="col-sm-7"><%= current_user.address %></div>

              <div class="clearfix"></div>
              <div class="bot-border"></div>

              <div class="col-sm-5 col-xs-6 tital " >Document:</div><div class="col-sm-7"><%= current_user.document %></div>

              <div class="clearfix"></div>
              <div class="bot-border"></div>

              <div class="col-sm-5 col-xs-6 tital " >Email:</div><div class="col-sm-7"><%= current_user.email %></div>


            </div>

          </div>


        </div>
      </div>
    </div>










  </div>
</div>

app/views/users_profiles/rentals.html.erb
<%= render "tabs" %>